### ISSUE TITLE
Send email notification when tour is started or ready for review

### ISSUE THREAD

**Issue by paveldruzyak** [yevhene/ikvn#21]
@yevhene треба щоб користувач міг підписуватись на різні тури/сезони/ліги чи одне глобальне поле яке визначає чи треба користувача сповіщати про старт?

**Comment by yevhene** [comment]
Одно глобальное поле в профиле. Дальше рассылка происходит по Participation.

**Comment by paveldruzyak** [comment]
@yevhene `wants_email` хороша назва для поля?

**Comment by yevhene** [comment]
@paveldruzyak :+1:

**Comment by paveldruzyak** [comment]
@yevhene rake таск раз в годину?

**Comment by yevhene** [comment]
@paveldruzyak Да думаю.
Для фоновых задач можно использовать sucker_punch. Ему не нужен отдельный воркер для хероку (он исполняется в том же процессе). У него есть адаптер к ActiveJob.
Но у него нет возможности запланировать задачу на время, так что пока да rake таск. Потом поменяем.
